# 1. Login as Manager
$login = Invoke-RestMethod -Uri 'http://localhost:5150/api/auth/login' -Method Post -ContentType 'application/json' -Body '{"email":"manager@stockflow.ai","password":"Manager@123"}'
Write-Host ">>> Logged in as: $($login.fullName) ($($login.role))"

$headers = @{ Authorization = "Bearer $($login.token)" }

# 2. Trigger AI Agent Reorder Workflow
Write-Host "`n>>> Starting AI Agent Reorder Pipeline..."
$body = @{
    objective = "Weekly inventory replenishment scan"
    triggerSource = "AutomatedScheduler"
} | ConvertTo-Json

$workflow = Invoke-RestMethod -Uri 'http://localhost:5150/api/agent/reorder' -Method Post -Headers $headers -ContentType 'application/json' -Body $body

Write-Host ">>> Workflow Created! ID: $($workflow.id)"
Write-Host ">>> Status: $($workflow.status)"
Write-Host ">>> Total Proposals Generated by AI: $($workflow.proposals.Count)"

foreach ($p in $workflow.proposals) {
    Write-Host "  -------------------------------------------------------"
    Write-Host "  Product: $($p.productName) ($($p.productSku))"
    Write-Host "  Current Stock: $($p.currentStock) units"
    Write-Host "  Proposed Reorder: $($p.proposedQuantity) units"
    Write-Host "  Estimated Cost: Rs. $($p.estimatedCost)"
    Write-Host "  Confidence Score: $($p.confidenceScore * 100)%"
    Write-Host "  Justification: $($p.justification)"
}

# 3. Human-in-the-loop Approval by Manager
Write-Host "`n>>> Simulating Manager Human-in-the-Loop Approval..."
$approvalBody = @{
    approved = $true
    notes = "Bulk discount verified with supplier. Approved for purchase."
} | ConvertTo-Json

$approvalResult = Invoke-RestMethod -Uri "http://localhost:5150/api/agent/workflows/$($workflow.id)/approve" -Method Post -Headers $headers -ContentType 'application/json' -Body $approvalBody

Write-Host ">>> Final Workflow Status: $($approvalResult.status)"
Write-Host ">>> Human-in-the-Loop Approval Gate: $($approvalResult.approvalGate.status)"
Write-Host ">>> Reviewed By: $($approvalResult.approvalGate.reviewedBy)"
